actions:
  player_command:
    #Should use playercommandpreprocessevent ?
    #true - if you need other plugins to listen to cancel or handle commands fired by items, like CombatLog MyCommands etc...
    fires_playercommandpreprocessevent: true
equipment_change:
  max_checked_players_per_tick: 3
  frequency_ticks: 5
